# Generated by Django 3.0.6 on 2020-08-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('COD', 'CashOnDelivery'), ('PAID', 'PREPAID')], default='COD', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('DE', 'Delivery'), ('CO', 'Completed')], default='PE', max_length=3),
        ),
    ]
